const String defaultScaffoldBgPath = 'assets/image/default_scaffold_background.png';
const blueButtonPath = 'assets/image/blue_button.png';
const orangeButtonPath = 'assets/image/orange_button.png';
const selectPuzzlePath = 'assets/image/select_puzzle.png';
const skipPath = 'assets/image/skip.png';
const hintPath = 'assets/image/hint.png';
const currentLevelBgPath = 'assets/image/currentLlevel_bg.png';
const questionBgPath = 'assets/image/question_bg.png';
const inputPath = 'assets/image/input.png';